### ISSUE TITLE
.vscode/settings.json: formatOnSave

### ISSUE THREAD

**Issue by blumk** [froko/ng-essentials#5]
Proposal:

add or modify the  `settings.json` with:

`"editor.formatOnSave": true`

**Comment by froko** [comment]
Not sure about this. I don't want to overwrite Visual Studio Code settings with the schematics. But I do agree with you, that this is a nice feature. This may be a topic for a blog post.

**Comment by froko** [comment]
@blumk settings.json is indeed a workspace setting. I didn't get that in the first place. So it's okay to add this feature. I will include it in the next version.

**Comment by froko** [comment]
Done ;-)
